spring:
  datasource:
    url: jdbc:mysql://localhost:3306/insurance_db?useSSL=false&serverTimezone=UTC
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
policy:
  document:
    path: ./policy-documents

server:
  port: 8080