spring:
  datasource:
    url: ${DATABASE_URL} # Railway will inject this
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

policy:
  document:
    path: /tmp/policy-docs # Railway-compatible path
